name: portfolio
description: Portfolio site for Jeroen Meijer. Only works on web.

version: 1.0.0

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get_it: 5.0.4
  very_good_analysis: 1.0.4
  yaml: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: 1.2.3
  pedantic: 1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - config.yaml
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons/AppIcons.ttf
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans/Product-Sans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Product-Sans/Product-Sans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Product-Sans/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product-Sans/Product-Sans-Bold-Italic.ttf
          weight: 700
          style: italic
    - family: Fira Code
      fonts:
        - asset: assets/fonts/Fira-Code/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira-Code/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fira-Code/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira-Code/FiraCode-Bold.ttf
          weight: 700
